# Generated by Django 4.0.4 on 2022-05-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
